In [1]:
import tensorflow as tf

In [2]:
a = 1.2

创建标量

In [3]:
aa = tf.constant(1.2)

In [4]:
type(a)

float

In [5]:
type(aa)

tensorflow.python.framework.ops.EagerTensor

In [6]:
tf.is_tensor(aa)

True

In [7]:
print(aa)

tf.Tensor(1.2, shape=(), dtype=float32)


In [8]:
x = tf.constant([1,2.,3.3])

In [9]:
x

<tf.Tensor: id=1, shape=(3,), dtype=float32, numpy=array([1. , 2. , 3.3], dtype=float32)>

id 是 TensorFlow 中内部索引对象的编号， shape 表示张量的形状， dtype 表示张量的数
值精度

numpy()方法可以返回 Numpy.array 类型的数据

In [10]:
x.numpy()

array([1. , 2. , 3.3], dtype=float32)

创建标量

In [11]:
a = tf.constant([1.2])

In [12]:
a, a.shape

(<tf.Tensor: id=2, shape=(1,), dtype=float32, numpy=array([1.2], dtype=float32)>,
 TensorShape([1]))

2个元素的向量

In [14]:
a = tf.constant([1,2,3.])

In [15]:
a, a.shape

(<tf.Tensor: id=3, shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>,
 TensorShape([3]))

定义矩阵

In [17]:
a = tf.constant([[1,2],[3,4]])

In [18]:
a, a.shape

(<tf.Tensor: id=4, shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>, TensorShape([2, 2]))

3维张量

In [20]:
a = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])

In [21]:
a, a.shape

(<tf.Tensor: id=5, shape=(2, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]], dtype=int32)>, TensorShape([2, 2, 2]))

字符串类型

In [22]:
a = tf.constant('Hello World')

In [23]:
a

<tf.Tensor: id=6, shape=(), dtype=string, numpy=b'Hello World'>

在 tf.strings 模块中，提供了常见的字符串型的工具函数，如拼接 join()，长度 length()，切
分 split()等等

In [24]:
tf.strings.lower(a)

<tf.Tensor: id=7, shape=(), dtype=string, numpy=b'hello world'>

布尔类型

In [26]:
a = tf.constant(True)

In [27]:
a

<tf.Tensor: id=8, shape=(), dtype=bool, numpy=True>

In [28]:
a = tf.constant([True,False])

In [29]:
a

<tf.Tensor: id=9, shape=(2,), dtype=bool, numpy=array([ True, False])>

In [34]:
a = tf.constant(True)
if a == True:
    print("success")
else:
    print("false")

success


数值精度

In [35]:
b = tf.constant(123456789, dtype=tf.int16)
c = tf.constant(123456789, dtype=tf.int32)

In [36]:
b,c

(<tf.Tensor: id=21, shape=(), dtype=int16, numpy=-13035>,
 <tf.Tensor: id=22, shape=(), dtype=int32, numpy=123456789>)

可以看到， 保存精度过低时，数据 123456789 发生了溢出， 得到了错误的结果

In [37]:
import numpy as np
np.pi
tf.constant(np.pi,dtype=tf.float32)

<tf.Tensor: id=23, shape=(), dtype=float32, numpy=3.1415927>

In [38]:
tf.constant(np.pi,dtype=tf.float64)

<tf.Tensor: id=24, shape=(), dtype=float64, numpy=3.141592653589793>

读取精度

In [39]:
print('before:',a.dtype)

before: <dtype: 'bool'>


类型转换

In [40]:
a = tf.constant(np.pi, dtype=tf.float16)

In [41]:
tf.cast(a,tf.double)

<tf.Tensor: id=26, shape=(), dtype=float64, numpy=3.140625>

将高精度张量转换为低精度张量，可能会发生数据溢出隐患

In [44]:
a = tf.constant(123456789, dtype=tf.int32)
tf.cast(a,tf.int16)

<tf.Tensor: id=29, shape=(), dtype=int16, numpy=-13035>

布尔型与整形之间相互转换也是合法的， 是比较常见的操作

In [46]:
a = tf.constant([True,False])
tf.cast(a,tf.int32)

<tf.Tensor: id=32, shape=(2,), dtype=int32, numpy=array([1, 0], dtype=int32)>

In [47]:
a = tf.constant([-1,0,1,2])
tf.cast(a,tf.bool)

<tf.Tensor: id=34, shape=(4,), dtype=bool, numpy=array([ True, False,  True,  True])>

待优化张量

In [48]:
a = tf.constant([-1,0,1,2])
aa = tf.Variable(a)
aa.name,aa.trainable

('Variable:0', True)

直接创建

In [50]:
a = tf.Variable([[1,2],[3,4]])
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

普通张量可以通过GradientTapt.watch()方法临时加入跟踪梯度信息的列表

创建张量

In [52]:
tf.convert_to_tensor([1,2.])

<tf.Tensor: id=58, shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [53]:
tf.convert_to_tensor(np.array([[1,2.],[3,4]]))

<tf.Tensor: id=59, shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

创建全 0，全 1 张量

In [54]:
tf.zeros([]),tf.ones([])

(<tf.Tensor: id=60, shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: id=61, shape=(), dtype=float32, numpy=1.0>)

创建全 0 和全 1 的向量

In [55]:
tf.zeros([1]),tf.ones([1])

(<tf.Tensor: id=64, shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Tensor: id=67, shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>)

创建全 0 的矩阵

In [57]:
tf.zeros([2,2])

<tf.Tensor: id=70, shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

创建全 1 的矩阵

In [58]:
tf.ones([3,2])

<tf.Tensor: id=73, shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

创建与张量 a 形状一样的全 0 张量

In [60]:
a = tf.ones([2,3])
tf.zeros_like(a)

<tf.Tensor: id=81, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

创建与张量 a 形状一样的全 1 张量

In [61]:
a = tf.zeros([3,2])
tf.ones_like(a)

<tf.Tensor: id=87, shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

创建自定义数值张量

In [62]:
tf.fill([],-1)

<tf.Tensor: id=90, shape=(), dtype=int32, numpy=-1>

创建所有元素为-1 的向量

In [63]:
tf.fill([1],-1)

<tf.Tensor: id=93, shape=(1,), dtype=int32, numpy=array([-1], dtype=int32)>

创建所有元素为 99 的矩阵：

In [64]:
tf.fill([2,2],99)

<tf.Tensor: id=96, shape=(2, 2), dtype=int32, numpy=
array([[99, 99],
       [99, 99]], dtype=int32)>

创建已知分布的张量

1.创建均值为0,标准差为1的正态分布

In [65]:
tf.random.normal([2,2])

<tf.Tensor: id=102, shape=(2, 2), dtype=float32, numpy=
array([[-0.571839  ,  1.2976298 ],
       [ 0.21529754,  0.9921046 ]], dtype=float32)>

创建均值为 1，标准差为 2 的正态分布

In [68]:
tf.random.normal([2,2],mean=1,stddev=2)

<tf.Tensor: id=114, shape=(2, 2), dtype=float32, numpy=
array([[ 0.32448035,  4.2583556 ],
       [-2.2416139 ,  3.8627129 ]], dtype=float32)>

2.创建均匀分布

In [69]:
tf.random.uniform([2,2])

<tf.Tensor: id=121, shape=(2, 2), dtype=float32, numpy=
array([[0.21537483, 0.8658372 ],
       [0.80189025, 0.7823967 ]], dtype=float32)>

创建采样自区间[0,10]， shape 为[2,2]的矩阵

In [70]:
tf.random.uniform([2,2],maxval=10)

<tf.Tensor: id=128, shape=(2, 2), dtype=float32, numpy=
array([[3.4099603, 2.384913 ],
       [8.664813 , 2.4867702]], dtype=float32)>

如果需要均匀采样整形类型的数据，必须指定采样区间的最大值 maxval 参数，同时制定数
据类型为 tf.int*型

In [72]:
tf.random.uniform([2,2],maxval=100,dtype=tf.int32)

<tf.Tensor: id=136, shape=(2, 2), dtype=int32, numpy=
array([[49, 50],
       [32, 69]], dtype=int32)>

创建序列

In [73]:
tf.range(10)

<tf.Tensor: id=140, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

创建 0~9，步长为 2 的整形序列

In [74]:
tf.range(10,delta=2)

<tf.Tensor: id=144, shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

In [75]:
tf.range(1,10,delta=2)

<tf.Tensor: id=148, shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

标量应用

In [76]:
out = tf.random.uniform([4,10]) #随机模拟网络输出
y = tf.constant([2,3,2,0]) #随机构造样本真实标签
y = tf.one_hot(y,depth=10) #one hot 编码
loss = tf.keras.losses.mse(y,out) #计算每个样本的MSE
loss = tf.reduce_mean(loss) #平均MSE
print(loss)

tf.Tensor(0.3248353, shape=(), dtype=float32)
