In [1]:
import tensorflow as tf

In [2]:
a = 1.2

创建标量

In [3]:
aa = tf.constant(1.2)

In [4]:
type(a)

float

In [5]:
type(aa)

tensorflow.python.framework.ops.EagerTensor

In [6]:
tf.is_tensor(aa)

True

In [7]:
print(aa)

tf.Tensor(1.2, shape=(), dtype=float32)


In [8]:
x = tf.constant([1,2.,3.3])

In [9]:
x

<tf.Tensor: id=1, shape=(3,), dtype=float32, numpy=array([1. , 2. , 3.3], dtype=float32)>

id 是 TensorFlow 中内部索引对象的编号， shape 表示张量的形状， dtype 表示张量的数
值精度

numpy()方法可以返回 Numpy.array 类型的数据

In [10]:
x.numpy()

array([1. , 2. , 3.3], dtype=float32)

创建标量

In [11]:
a = tf.constant([1.2])

In [12]:
a, a.shape

(<tf.Tensor: id=2, shape=(1,), dtype=float32, numpy=array([1.2], dtype=float32)>,
 TensorShape([1]))

2个元素的向量

In [14]:
a = tf.constant([1,2,3.])

In [15]:
a, a.shape

(<tf.Tensor: id=3, shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>,
 TensorShape([3]))

定义矩阵

In [17]:
a = tf.constant([[1,2],[3,4]])

In [18]:
a, a.shape

(<tf.Tensor: id=4, shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>, TensorShape([2, 2]))

3维张量

In [20]:
a = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])

In [21]:
a, a.shape

(<tf.Tensor: id=5, shape=(2, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]], dtype=int32)>, TensorShape([2, 2, 2]))

字符串类型

In [22]:
a = tf.constant('Hello World')

In [23]:
a

<tf.Tensor: id=6, shape=(), dtype=string, numpy=b'Hello World'>

在 tf.strings 模块中，提供了常见的字符串型的工具函数，如拼接 join()，长度 length()，切
分 split()等等

In [24]:
tf.strings.lower(a)

<tf.Tensor: id=7, shape=(), dtype=string, numpy=b'hello world'>

布尔类型

In [26]:
a = tf.constant(True)

In [27]:
a

<tf.Tensor: id=8, shape=(), dtype=bool, numpy=True>

In [28]:
a = tf.constant([True,False])

In [29]:
a

<tf.Tensor: id=9, shape=(2,), dtype=bool, numpy=array([ True, False])>

In [34]:
a = tf.constant(True)
if a == True:
    print("success")
else:
    print("false")

success


数值精度

In [35]:
b = tf.constant(123456789, dtype=tf.int16)
c = tf.constant(123456789, dtype=tf.int32)

In [36]:
b,c

(<tf.Tensor: id=21, shape=(), dtype=int16, numpy=-13035>,
 <tf.Tensor: id=22, shape=(), dtype=int32, numpy=123456789>)

可以看到， 保存精度过低时，数据 123456789 发生了溢出， 得到了错误的结果

In [37]:
import numpy as np
np.pi
tf.constant(np.pi,dtype=tf.float32)

<tf.Tensor: id=23, shape=(), dtype=float32, numpy=3.1415927>

In [38]:
tf.constant(np.pi,dtype=tf.float64)

<tf.Tensor: id=24, shape=(), dtype=float64, numpy=3.141592653589793>

读取精度

In [39]:
print('before:',a.dtype)

before: <dtype: 'bool'>


类型转换

In [40]:
a = tf.constant(np.pi, dtype=tf.float16)

In [41]:
tf.cast(a,tf.double)

<tf.Tensor: id=26, shape=(), dtype=float64, numpy=3.140625>

将高精度张量转换为低精度张量，可能会发生数据溢出隐患

In [44]:
a = tf.constant(123456789, dtype=tf.int32)
tf.cast(a,tf.int16)

<tf.Tensor: id=29, shape=(), dtype=int16, numpy=-13035>

布尔型与整形之间相互转换也是合法的， 是比较常见的操作

In [46]:
a = tf.constant([True,False])
tf.cast(a,tf.int32)

<tf.Tensor: id=32, shape=(2,), dtype=int32, numpy=array([1, 0], dtype=int32)>

In [47]:
a = tf.constant([-1,0,1,2])
tf.cast(a,tf.bool)

<tf.Tensor: id=34, shape=(4,), dtype=bool, numpy=array([ True, False,  True,  True])>

待优化张量

In [48]:
a = tf.constant([-1,0,1,2])
aa = tf.Variable(a)
aa.name,aa.trainable

('Variable:0', True)

直接创建

In [50]:
a = tf.Variable([[1,2],[3,4]])
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

普通张量可以通过GradientTapt.watch()方法临时加入跟踪梯度信息的列表

创建张量

In [52]:
tf.convert_to_tensor([1,2.])

<tf.Tensor: id=58, shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [53]:
tf.convert_to_tensor(np.array([[1,2.],[3,4]]))

<tf.Tensor: id=59, shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

创建全 0，全 1 张量

In [54]:
tf.zeros([]),tf.ones([])

(<tf.Tensor: id=60, shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: id=61, shape=(), dtype=float32, numpy=1.0>)

创建全 0 和全 1 的向量

In [55]:
tf.zeros([1]),tf.ones([1])

(<tf.Tensor: id=64, shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Tensor: id=67, shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>)

创建全 0 的矩阵

In [57]:
tf.zeros([2,2])

<tf.Tensor: id=70, shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

创建全 1 的矩阵

In [58]:
tf.ones([3,2])

<tf.Tensor: id=73, shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

创建与张量 a 形状一样的全 0 张量

In [60]:
a = tf.ones([2,3])
tf.zeros_like(a)

<tf.Tensor: id=81, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

创建与张量 a 形状一样的全 1 张量

In [61]:
a = tf.zeros([3,2])
tf.ones_like(a)

<tf.Tensor: id=87, shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

创建自定义数值张量

In [62]:
tf.fill([],-1)

<tf.Tensor: id=90, shape=(), dtype=int32, numpy=-1>

创建所有元素为-1 的向量

In [63]:
tf.fill([1],-1)

<tf.Tensor: id=93, shape=(1,), dtype=int32, numpy=array([-1], dtype=int32)>

创建所有元素为 99 的矩阵：

In [64]:
tf.fill([2,2],99)

<tf.Tensor: id=96, shape=(2, 2), dtype=int32, numpy=
array([[99, 99],
       [99, 99]], dtype=int32)>

创建已知分布的张量

1.创建均值为0,标准差为1的正态分布

In [65]:
tf.random.normal([2,2])

<tf.Tensor: id=102, shape=(2, 2), dtype=float32, numpy=
array([[-0.571839  ,  1.2976298 ],
       [ 0.21529754,  0.9921046 ]], dtype=float32)>

创建均值为 1，标准差为 2 的正态分布

In [68]:
tf.random.normal([2,2],mean=1,stddev=2)

<tf.Tensor: id=114, shape=(2, 2), dtype=float32, numpy=
array([[ 0.32448035,  4.2583556 ],
       [-2.2416139 ,  3.8627129 ]], dtype=float32)>

2.创建均匀分布

In [69]:
tf.random.uniform([2,2])

<tf.Tensor: id=121, shape=(2, 2), dtype=float32, numpy=
array([[0.21537483, 0.8658372 ],
       [0.80189025, 0.7823967 ]], dtype=float32)>

创建采样自区间[0,10]， shape 为[2,2]的矩阵

In [70]:
tf.random.uniform([2,2],maxval=10)

<tf.Tensor: id=128, shape=(2, 2), dtype=float32, numpy=
array([[3.4099603, 2.384913 ],
       [8.664813 , 2.4867702]], dtype=float32)>

如果需要均匀采样整形类型的数据，必须指定采样区间的最大值 maxval 参数，同时制定数
据类型为 tf.int*型

In [72]:
tf.random.uniform([2,2],maxval=100,dtype=tf.int32)

<tf.Tensor: id=136, shape=(2, 2), dtype=int32, numpy=
array([[49, 50],
       [32, 69]], dtype=int32)>

创建序列

In [73]:
tf.range(10)

<tf.Tensor: id=140, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

创建 0~9，步长为 2 的整形序列

In [74]:
tf.range(10,delta=2)

<tf.Tensor: id=144, shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

In [75]:
tf.range(1,10,delta=2)

<tf.Tensor: id=148, shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

标量应用

In [76]:
out = tf.random.uniform([4,10]) #随机模拟网络输出
y = tf.constant([2,3,2,0]) #随机构造样本真实标签
y = tf.one_hot(y,depth=10) #one hot 编码
loss = tf.keras.losses.mse(y,out) #计算每个样本的MSE
loss = tf.reduce_mean(loss) #平均MSE
print(loss)

tf.Tensor(0.3248353, shape=(), dtype=float32)


向量

In [2]:
z = tf.random.normal([4,2]) #z=wx,模拟获得激活函数的输入 z

In [3]:
b = tf.zeros([2]) #模拟偏置向量

In [5]:
z = z + b  #累加偏置
z

<tf.Tensor: id=10, shape=(4, 2), dtype=float32, numpy=
array([[ 0.15070744,  0.3171254 ],
       [ 1.250352  , -1.0780892 ],
       [ 0.88869125, -0.5843592 ],
       [-1.3788879 , -0.76072395]], dtype=float32)>

In [9]:
fc = tf.keras.layers.Dense(3) # 创建一层 Wx+b，输出节点为 3
fc.build(input_shape=(2,4)) # 通过 build 函数创建 W,b 张量，输入节点为 4
fc.bias  # 查看偏置

<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

矩阵

In [10]:
x = tf.random.normal([2,4])
w = tf.ones([4,3]) # 定义 W 张量
b = tf.zeros([3])  # 定义 b 张量
o = x@w+b   # X@W+b 运算
o

<tf.Tensor: id=49, shape=(2, 3), dtype=float32, numpy=
array([[-1.2177361 , -1.2177361 , -1.2177361 ],
       [ 0.24091548,  0.24091548,  0.24091548]], dtype=float32)>

In [11]:
fc = tf.keras.layers.Dense(3) # 创建一层 Wx+b，输出节点为 3
fc.build(input_shape=(2,4)) # 通过 build 函数创建 W,b 张量，输入节点为 4
fc.kernel

<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[-0.01358432,  0.4953959 , -0.11235762],
       [ 0.5869466 ,  0.23385525,  0.6524718 ],
       [-0.371781  , -0.4754243 , -0.79318976],
       [-0.4303162 ,  0.19100201, -0.07961386]], dtype=float32)>

索引与切片

In [12]:
# 创建 32x32 的彩色图片输入，个数为 4
x = tf.random.normal([4,32,32,3])

取第 3 张图片，第 2 行，第 1 列的像素， B 通道(第 2 个通道)颜色强度值：

In [14]:
x[2,1,0,1]

<tf.Tensor: id=87, shape=(), dtype=float32, numpy=1.1600045>

切片

读取第 2,3 张图片

In [15]:
x[1:3]

<tf.Tensor: id=91, shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[ 3.9608958e-01,  1.1666833e+00, -9.5961040e-01],
         [ 7.5062625e-02, -1.6343539e+00, -6.5661925e-01],
         [ 8.2059348e-01, -4.9437222e-01,  1.9591441e-02],
         ...,
         [-1.3620663e+00, -1.0308050e+00,  9.7981751e-01],
         [-4.6695253e-01, -3.3674836e-01,  1.1081425e+00],
         [ 9.1062981e-01,  1.3964354e+00,  2.4595003e-01]],

        [[-3.6236784e-01,  9.3415696e-03,  9.7871274e-01],
         [ 1.5890433e+00, -2.0541415e+00,  7.7621257e-01],
         [-6.1750573e-01, -7.4248952e-01, -2.6333258e+00],
         ...,
         [ 9.5234823e-01, -9.3141317e-01, -3.1923255e-01],
         [-1.8288110e+00, -9.7536363e-02,  2.7277274e+00],
         [-1.0575179e+00, -1.5638824e+00,  3.4658501e-01]],

        [[-9.6560717e-01, -9.9528837e-01,  2.4339932e-01],
         [ 4.5681235e-01,  2.5524205e-01, -1.1690129e+00],
         [-1.0564183e+00, -3.7195179e-01, -7.9225731e-01],
         ...,
      

start: end: step切片方式有很多简写方式，其中 start、 end、 step 3 个参数可以根据需要
选择性地省略， 全部省略时即::， 表示从最开始读取到最末尾，步长为 1，即不跳过任何元
素。 如 x[0,::]表示读取第 1 张图片的所有行， 其中::表示在行维度上读取所有行，它等于
x[0]的写法：

In [16]:
x[0,::]

<tf.Tensor: id=95, shape=(32, 32, 3), dtype=float32, numpy=
array([[[ 0.26458853,  0.6862444 , -1.5623252 ],
        [-0.87364644, -1.0548266 ,  2.1718805 ],
        [ 0.07239671, -1.5428709 ,  0.60088605],
        ...,
        [-2.584377  ,  0.25847468, -2.1008103 ],
        [-0.5777474 ,  0.24534662,  0.63605446],
        [-1.4661803 , -0.02201184,  1.1565276 ]],

       [[-0.8461384 ,  1.0477241 , -0.91011983],
        [ 0.57177323, -0.6644301 , -0.00612693],
        [ 1.4064115 , -0.0878811 , -0.45680508],
        ...,
        [-0.11536597,  0.5707641 , -0.72139716],
        [-0.5091206 , -0.57347465,  0.6009836 ],
        [ 0.5171234 , -0.58001757,  0.83449274]],

       [[-1.1543097 ,  0.6921324 , -0.10571495],
        [ 0.04353014, -3.6674335 , -0.8843712 ],
        [-1.2045063 ,  0.05437936, -0.58556515],
        ...,
        [ 0.40672207,  0.13439499,  0.35402346],
        [ 0.8968141 , -1.274659  , -1.6582727 ],
        [ 0.16549163,  1.3120817 , -1.1174604 ]],

       ...,



为了更加简洁， ::可以简写为单个冒号:，

In [17]:
x[:,0:28:2,0:28:2,:]

<tf.Tensor: id=99, shape=(4, 14, 14, 3), dtype=float32, numpy=
array([[[[ 2.64588535e-01,  6.86244428e-01, -1.56232524e+00],
         [ 7.23967105e-02, -1.54287088e+00,  6.00886047e-01],
         [-1.83958024e-01,  1.48256886e+00,  6.64869428e-01],
         ...,
         [ 7.64228404e-01,  9.21247482e-01, -8.35385621e-01],
         [-1.33977401e+00,  1.13132465e+00,  1.65383115e-01],
         [ 9.22469199e-01,  2.36471117e-01,  3.03110051e+00]],

        [[-1.15430975e+00,  6.92132413e-01, -1.05714947e-01],
         [-1.20450628e+00,  5.43793552e-02, -5.85565150e-01],
         [-1.32450485e+00,  2.10647389e-01, -1.12691712e+00],
         ...,
         [-9.39074516e-01, -2.61862546e-01, -2.20228410e+00],
         [ 2.09112525e+00, -1.53537703e+00, -1.56233692e+00],
         [ 1.66733611e+00, -3.89993489e-01, -1.73464763e+00]],

        [[ 2.88183302e-01,  1.61201194e-01, -2.22069383e-01],
         [-3.60703111e-01, -1.10041904e+00, -1.01736939e+00],
         [ 5.69621734e-02, -1.5579227

step=-1时

In [19]:
x = tf.range(9)
x

<tf.Tensor: id=107, shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

逆序取到第 1 号元素，不包含第 1 号

In [20]:
x[8:0:-1]

<tf.Tensor: id=111, shape=(8,), dtype=int32, numpy=array([8, 7, 6, 5, 4, 3, 2, 1], dtype=int32)>

逆序取全部元素

In [21]:
x[::-1]

<tf.Tensor: id=115, shape=(9,), dtype=int32, numpy=array([8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int32)>

逆序间隔采样：

In [22]:
x[::-2]

<tf.Tensor: id=119, shape=(5,), dtype=int32, numpy=array([8, 6, 4, 2, 0], dtype=int32)>

读取每张图片的所有通道，其中行按着逆序隔行采样，列按着逆序隔行采样

In [25]:
x = tf.random.normal([4,32,32,3])
x[0,::-2,::-2]

<tf.Tensor: id=139, shape=(16, 16, 3), dtype=float32, numpy=
array([[[ 1.7076184 , -0.5444677 , -1.3459275 ],
        [ 1.2990867 , -0.6740708 ,  1.0272897 ],
        [ 1.6500206 , -0.95017153,  0.9988256 ],
        [-0.04928169,  0.6438419 , -1.3719759 ],
        [-0.5772684 , -0.31549358,  1.3918805 ],
        [ 0.42881864, -0.17654087,  0.14669144],
        [-0.49119735,  0.26027623,  0.52740186],
        [-0.24282514, -0.456638  , -0.5282373 ],
        [ 1.0869583 , -1.0092403 ,  0.5790364 ],
        [ 1.0723886 ,  1.0964345 , -0.39718738],
        [-0.7441917 ,  0.7352037 ,  0.6292965 ],
        [-0.15156165, -0.2353696 ,  0.13729136],
        [-1.1921936 ,  2.2766154 , -0.42525056],
        [ 0.17872232, -0.53978467, -0.6836645 ],
        [-0.06291558, -0.75408083,  0.3595756 ],
        [-0.13884266,  0.57396317, -0.37977764]],

       [[-1.488756  ,  2.0465953 ,  0.43124032],
        [-1.1662396 ,  0.681597  ,  0.08120437],
        [ 1.4840999 , -0.23165964,  0.58834726],
      

当需要读取 G 通道上的数据
时，前面所有维度全部提取

In [26]:
x[:,:,:,1]

<tf.Tensor: id=143, shape=(4, 32, 32), dtype=float32, numpy=
array([[[ 0.97672015, -0.49107623, -0.70859826, ..., -1.1026745 ,
         -0.91111016, -0.15795557],
        [ 1.0738639 , -0.23373327, -0.1989854 , ..., -0.83456343,
          0.05154002, -1.328726  ],
        [ 1.2795941 , -1.4797685 , -0.40197465, ...,  1.1367092 ,
         -1.4507173 , -0.89771235],
        ...,
        [-1.3909503 , -0.26603937,  0.42820105, ...,  0.681597  ,
          0.892019  ,  2.0465953 ],
        [ 2.2494545 , -2.0616376 ,  0.14103268, ...,  0.2593796 ,
          1.2422541 ,  1.5982071 ],
        [ 0.9512501 ,  0.57396317,  0.78060377, ..., -0.6740708 ,
          2.1235204 , -0.5444677 ]],

       [[ 1.112748  ,  1.1064278 ,  0.39678282, ...,  0.96460474,
         -1.9400271 , -1.6145859 ],
        [-0.11087621, -1.1669091 , -0.9373415 , ...,  0.2928574 ,
          0.8366332 ,  1.0534027 ],
        [-0.14332461,  0.18483129, -1.4776647 , ..., -0.23642106,
          0.08141276, -0.15749174],
      

为了避免出现像𝑥[: , : , : ,1]这样出现过多冒号的情况，可以使用⋯符号表示取多个维度
上所有的数据， 其中维度的数量需根据规则自动推断：当切片方式出现⋯符号时， ⋯符号
左边的维度将自动对齐到最左边， ⋯符号右边的维度将自动对齐到最右边，此时系统再自
动推断⋯符号代表的维度数量，它的切片方式总结如下：

|切片方式|意义|
|-|-|
|a,⋯,b|a 维度对齐到最左边， b 维度对齐到最右边，中间的维度全部读取，其他维度按 a/b 的方式读取|
|a,⋯ |a 维度对齐到最左边， a 维度后的所有维度全部读取， a 维度按 a 方式读取。这种情况等同于 a 索引/切片方式|
|⋯,b |b 维度对齐到最右边， b 之前的所有维度全部读取， b 维度按 b 方式读取|
|⋯ |读取张量所有数据|

读取第 1-2 张图片的 G/B 通道数据

In [28]:
x[0:2,...,1:]

<tf.Tensor: id=147, shape=(2, 32, 32, 2), dtype=float32, numpy=
array([[[[ 0.97672015,  0.4603718 ],
         [-0.49107623,  0.06701498],
         [-0.70859826,  0.5660286 ],
         ...,
         [-1.1026745 , -0.15162228],
         [-0.91111016,  0.8319928 ],
         [-0.15795557, -0.45906356]],

        [[ 1.0738639 ,  1.4060162 ],
         [-0.23373327,  0.32794675],
         [-0.1989854 , -0.54550385],
         ...,
         [-0.83456343,  0.3975246 ],
         [ 0.05154002, -1.5098771 ],
         [-1.328726  ,  1.2026855 ]],

        [[ 1.2795941 , -1.7254738 ],
         [-1.4797685 , -0.70065534],
         [-0.40197465,  0.45349523],
         ...,
         [ 1.1367092 ,  0.59552443],
         [-1.4507173 , -0.18474379],
         [-0.89771235, -0.508731  ]],

        ...,

        [[-1.3909503 , -1.231666  ],
         [-0.26603937, -1.7190018 ],
         [ 0.42820105, -0.18879545],
         ...,
         [ 0.681597  ,  0.08120437],
         [ 0.892019  , -0.3439483 ],
         

读取最后 2 张图片

In [29]:
x[2:,...]

<tf.Tensor: id=151, shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[-1.4069071 ,  0.66953725,  1.8361789 ],
         [-1.0405965 , -0.4626473 ,  2.1288238 ],
         [-1.5338409 , -1.2519552 , -1.2817392 ],
         ...,
         [-0.21800065,  1.7969759 ,  2.3351045 ],
         [-2.3055615 , -0.11216547, -1.8903465 ],
         [-0.05353056,  2.5283506 , -1.3348974 ]],

        [[-1.3838996 ,  0.62614   , -1.0276469 ],
         [ 0.1156114 ,  0.10272039, -0.665676  ],
         [-1.5951    ,  0.7563804 ,  0.07366824],
         ...,
         [ 1.3909926 ,  0.9540902 , -0.20861392],
         [ 1.3329881 ,  1.7720574 ,  0.29327628],
         [-0.08888812, -2.0599577 , -0.14053485]],

        [[ 0.4488321 , -0.45515227, -0.6322353 ],
         [ 0.28268942, -1.9960983 , -1.5518869 ],
         [-2.4109185 , -0.31773612, -0.14268124],
         ...,
         [ 0.8603115 , -1.1191639 ,  0.9027255 ],
         [-1.1832116 ,  1.2504061 ,  1.014112  ],
         [ 0.820445  ,  0.36137825,  0.7

读取 R/G 通道数据

In [30]:
x[...,:2]

<tf.Tensor: id=155, shape=(4, 32, 32, 2), dtype=float32, numpy=
array([[[[-0.70895666,  0.97672015],
         [ 0.36162984, -0.49107623],
         [ 1.2069854 , -0.70859826],
         ...,
         [ 1.6082137 , -1.1026745 ],
         [ 1.0661865 , -0.91111016],
         [ 0.68218374, -0.15795557]],

        [[ 0.31088117,  1.0738639 ],
         [-0.73644334, -0.23373327],
         [ 2.8944006 , -0.1989854 ],
         ...,
         [ 0.10756447, -0.83456343],
         [ 0.48495084,  0.05154002],
         [ 0.91232145, -1.328726  ]],

        [[-0.03945472,  1.2795941 ],
         [-0.21200061, -1.4797685 ],
         [-0.80729324, -0.40197465],
         ...,
         [ 0.32206896,  1.1367092 ],
         [-1.2263781 , -1.4507173 ],
         [ 0.54238534, -0.89771235]],

        ...,

        [[-0.07257909, -1.3909503 ],
         [ 1.3036939 , -0.26603937],
         [-0.15336335,  0.42820105],
         ...,
         [-1.1662396 ,  0.681597  ],
         [-0.1862786 ,  0.892019  ],
         

Reshape

In [31]:
x = tf.range(96)
x =tf.reshape(x,[2,4,4,3])
x

<tf.Tensor: id=161, shape=(2, 4, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]], dtype=int32)>

In [32]:
x.ndim,x.shape

(4, TensorShape([2, 4, 4, 3]))

In [33]:
tf.reshape(x,[2,-1])

<tf.Tensor: id=163, shape=(2, 48), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]],
      dtype=int32)>

其中的参数-1 表示当前轴上长度需要根据视图总元素不变的法则自动推导， 从而方便用户书写。 比如，上面的-1 可以推导 (2* 4 * 4*3)/2 = 48

In [34]:
#再次改变数据的视图为[2,16,3]
tf.reshape(x,[2,-1,3])

<tf.Tensor: id=165, shape=(2, 16, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47]],

       [[48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59],
        [60, 61, 62],
        [63, 64, 65],
        [66, 67, 68],
        [69, 70, 71],
        [72, 73, 74],
        [75, 76, 77],
        [78, 79, 80],
        [81, 82, 83],
        [84, 85, 86],
        [87, 88, 89],
        [90, 91, 92],
        [93, 94, 95]]], dtype=int32)>

增删维度

考虑一个具体例子，一张 28x28 灰度图片的数据保存为 shape 为[28,28]的张量， 在末
尾给张量增加一新维度， 定义为为通道数维度，此时张量的 shape 变为[28,28,1]

In [40]:
x = tf.random.uniform([28,28],maxval=10,dtype=tf.int32)
x

<tf.Tensor: id=183, shape=(28, 28), dtype=int32, numpy=
array([[7, 8, 0, 6, 6, 0, 0, 1, 3, 8, 1, 6, 5, 5, 7, 0, 9, 7, 8, 2, 8, 6,
        9, 0, 8, 1, 1, 2],
       [0, 5, 0, 4, 1, 9, 9, 0, 1, 2, 0, 2, 1, 2, 7, 0, 5, 5, 7, 3, 3, 6,
        9, 0, 1, 0, 6, 2],
       [0, 3, 1, 6, 9, 7, 3, 6, 4, 0, 1, 6, 4, 3, 9, 7, 7, 2, 6, 8, 9, 2,
        3, 0, 1, 0, 4, 4],
       [8, 5, 8, 6, 2, 9, 8, 4, 7, 6, 4, 9, 7, 4, 0, 5, 3, 2, 0, 8, 2, 4,
        5, 1, 2, 5, 5, 2],
       [9, 0, 8, 5, 3, 8, 1, 0, 2, 6, 3, 3, 8, 9, 7, 9, 5, 8, 6, 0, 4, 4,
        7, 1, 1, 8, 3, 6],
       [7, 2, 4, 5, 8, 0, 0, 8, 0, 2, 7, 8, 5, 3, 2, 5, 0, 5, 8, 7, 4, 8,
        6, 4, 3, 4, 4, 3],
       [9, 5, 6, 5, 7, 6, 2, 7, 4, 6, 1, 9, 9, 1, 7, 3, 8, 2, 2, 0, 4, 5,
        8, 3, 6, 4, 0, 9],
       [9, 7, 6, 6, 5, 6, 2, 0, 1, 8, 5, 9, 5, 8, 8, 8, 2, 5, 1, 3, 7, 9,
        5, 1, 6, 9, 7, 5],
       [5, 6, 3, 3, 2, 3, 2, 3, 1, 5, 7, 1, 1, 6, 8, 8, 0, 0, 9, 6, 6, 9,
        7, 1, 5, 8, 6, 8],
       [2, 9, 4, 5, 6, 8, 9, 4, 5, 

In [41]:
x = tf.expand_dims(x,axis=2)
x

<tf.Tensor: id=185, shape=(28, 28, 1), dtype=int32, numpy=
array([[[7],
        [8],
        [0],
        [6],
        [6],
        [0],
        [0],
        [1],
        [3],
        [8],
        [1],
        [6],
        [5],
        [5],
        [7],
        [0],
        [9],
        [7],
        [8],
        [2],
        [8],
        [6],
        [9],
        [0],
        [8],
        [1],
        [1],
        [2]],

       [[0],
        [5],
        [0],
        [4],
        [1],
        [9],
        [9],
        [0],
        [1],
        [2],
        [0],
        [2],
        [1],
        [2],
        [7],
        [0],
        [5],
        [5],
        [7],
        [3],
        [3],
        [6],
        [9],
        [0],
        [1],
        [0],
        [6],
        [2]],

       [[0],
        [3],
        [1],
        [6],
        [9],
        [7],
        [3],
        [6],
        [4],
        [0],
        [1],
        [6],
        [4],
        [3],
        [9],
        [7],
 

In [42]:
x = tf.expand_dims(x,axis=0)
x.shape

TensorShape([1, 28, 28, 1])

需要注意的是， tf.expand_dims 的 axis 为正时，表示在当前维度之前插入一个新维度； 为负时，表示当前维度之后插入一个新的维度。

删除维度

删除维度只能删除长度为 1 的维度，也不会改变张量的存储。 

In [43]:
x = tf.squeeze(x,axis=0)
x.shape

TensorShape([28, 28, 1])

In [44]:
x = tf.squeeze(x,axis=2)
x.shape

TensorShape([28, 28])

如果不指定维度参数 axis，即 tf.squeeze(x)， 那么他会默认删除所有长度为 1 的维度：

In [46]:
x = tf.random.uniform([1,28,28,1],maxval=10,dtype=tf.int32)
x.shape

TensorShape([1, 28, 28, 1])

In [47]:
x = tf.squeeze(x)
x.shape

TensorShape([28, 28])

交换维度