In [1]:
import tensorflow as tf

交换维度、数据复制、Broadcasting

In [2]:
x = tf.random.normal([2,32,32,3])
x.shape

TensorShape([2, 32, 32, 3])

In [5]:
tf.transpose(x,perm=[0,3,1,2])


<tf.Tensor: id=11, shape=(2, 3, 32, 32), dtype=float32, numpy=
array([[[[ 4.2748994e-01, -1.2576958e+00, -5.9312806e-02, ...,
          -7.1338439e-01,  4.9411869e-01,  7.7314812e-01],
         [ 2.1269147e+00, -1.3882776e+00, -5.0939566e-01, ...,
          -9.3622750e-01,  1.8766557e+00,  7.8655303e-01],
         [-1.9123328e-01, -5.5938953e-01,  1.8140001e+00, ...,
           2.3689826e-01, -6.6345841e-01, -6.6294074e-01],
         ...,
         [-1.5329078e+00,  1.0117419e+00,  9.7708666e-01, ...,
           7.7070326e-01, -5.4085684e-01,  2.4483556e-01],
         [-4.8822576e-01,  3.1006087e-02, -1.9131248e-01, ...,
          -1.6611650e+00,  4.5114022e-01, -1.9801877e+00],
         [ 6.3177687e-01,  1.0961111e+00, -7.5431728e-01, ...,
           4.3012890e-01, -4.6355009e-01, -4.2060080e-01]],

        [[-5.6908023e-01,  3.3369163e-01, -4.6107495e-01, ...,
          -4.5334655e-01, -2.0339181e-01, -8.5111481e-01],
         [-5.7444191e-01, -1.5356694e+00,  4.8045736e-02, ...,
    

In [6]:
x.shape

TensorShape([2, 32, 32, 3])

In [10]:
x = tf.transpose(x,perm=[0,3,1,2])
x.shape

TensorShape([2, 32, 3, 32])

数据复制

In [15]:
b = tf.constant([1,2])
b = tf.expand_dims(b,axis=0)
b

<tf.Tensor: id=29, shape=(1, 2), dtype=int32, numpy=array([[1, 2]], dtype=int32)>

通过 tf.tile(b, multiples=[2,1])即可在 axis=0 维度复制 1 次，在 axis=1 维度不复制。

In [16]:
b = tf.tile(b,multiples=[2,1])
b

<tf.Tensor: id=31, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 2]], dtype=int32)>

In [20]:
x = tf.range(4)
x = tf.reshape(x,[2,2])
x

<tf.Tensor: id=47, shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3]], dtype=int32)>

In [21]:
x = tf.tile(x,multiples=[1,2])
x

<tf.Tensor: id=49, shape=(2, 4), dtype=int32, numpy=
array([[0, 1, 0, 1],
       [2, 3, 2, 3]], dtype=int32)>

In [22]:
x = tf.tile(x,multiples=[2,1])
x

<tf.Tensor: id=51, shape=(4, 4), dtype=int32, numpy=
array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3]], dtype=int32)>

Broadcasting

In [23]:
x = tf.random.normal([2,4])
w = tf.random.normal([4,3])
b = tf.random.normal([3])
y = x@w+b
y

<tf.Tensor: id=71, shape=(2, 3), dtype=float32, numpy=
array([[ 1.5852001 ,  0.8984506 , -3.700715  ],
       [-0.11051995, -0.71987796, -0.460757  ]], dtype=float32)>

上述加法并没有发生逻辑错误，那么它是怎么实现的呢？ 这是因为它自动调用 Broadcasting
函数 tf.broadcast_to(x, new_shape)， 将 2 者 shape 扩张为相同的[2,3]， 即上式可以等效为：

In [24]:
y = x@w + tf.broadcast_to(b,[2,3])
y

<tf.Tensor: id=75, shape=(2, 3), dtype=float32, numpy=
array([[ 1.5852001 ,  0.8984506 , -3.700715  ],
       [-0.11051995, -0.71987796, -0.460757  ]], dtype=float32)>

In [25]:
A = tf.random.normal([32,1])
tf.broadcast_to(A,[2,32,32,3])

<tf.Tensor: id=83, shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[ 1.3066666 ,  1.3066666 ,  1.3066666 ],
         [ 0.33408147,  0.33408147,  0.33408147],
         [ 1.3133459 ,  1.3133459 ,  1.3133459 ],
         ...,
         [-0.18468933, -0.18468933, -0.18468933],
         [-2.0111716 , -2.0111716 , -2.0111716 ],
         [-0.01120123, -0.01120123, -0.01120123]],

        [[ 1.3066666 ,  1.3066666 ,  1.3066666 ],
         [ 0.33408147,  0.33408147,  0.33408147],
         [ 1.3133459 ,  1.3133459 ,  1.3133459 ],
         ...,
         [-0.18468933, -0.18468933, -0.18468933],
         [-2.0111716 , -2.0111716 , -2.0111716 ],
         [-0.01120123, -0.01120123, -0.01120123]],

        [[ 1.3066666 ,  1.3066666 ,  1.3066666 ],
         [ 0.33408147,  0.33408147,  0.33408147],
         [ 1.3133459 ,  1.3133459 ,  1.3133459 ],
         ...,
         [-0.18468933, -0.18468933, -0.18468933],
         [-2.0111716 , -2.0111716 , -2.0111716 ],
         [-0.01120123, -0.01120123, -0.01

在 c 维度上，张量已经有 2 个特征数据， 新 shape 对应维度长度为 c(𝑐 ≠ 2，比如 c=3)，那
么当前维度上的这 2 个特征无法普适到其他长度，故不满足普适性原则，无法应用
Broadcasting 机制，将会触发错误

In [26]:
A = tf.random.normal([32,2])
tf.broadcast_to(A,[2,32,32,4])

InvalidArgumentError: Incompatible shapes: [32,2] vs. [2,32,32,4] [Op:BroadcastTo]

In [27]:
a = tf.random.normal([2,32,32,1])
b = tf.random.normal([32,32])
a+b,a-b,a*b,a/b

(<tf.Tensor: id=103, shape=(2, 32, 32, 32), dtype=float32, numpy=
 array([[[[ 2.67939568e+00,  1.50443876e+00,  1.67854536e+00, ...,
           -8.05414915e-02, -6.06279850e-01,  2.70131016e+00],
          [ 3.53198409e+00,  1.67677546e+00,  2.22722054e+00, ...,
            2.20430207e+00,  2.89233565e+00,  1.95959425e+00],
          [ 2.97450602e-01,  1.27003193e+00,  1.90319800e+00, ...,
           -2.05874276e+00, -6.76838934e-01, -2.51634955e+00],
          ...,
          [ 1.76456416e+00,  9.42317009e-01, -1.54545903e-03, ...,
           -7.66924143e-01,  9.26673472e-01, -3.05421382e-01],
          [-8.77875924e-01, -2.64203858e+00, -1.57787228e+00, ...,
           -1.50337696e+00, -3.68875027e-01, -7.05337584e-01],
          [-1.76807344e+00,  1.23770809e+00, -4.11019981e-01, ...,
           -4.84319419e-01,  2.92537928e-01,  3.16216350e-02]],
 
         [[ 2.35663271e+00,  1.18167567e+00,  1.35578227e+00, ...,
           -4.03304577e-01, -9.29042935e-01,  2.37854719e+00],
      