In [1]:
import tensorflow as tf

加减乘除

In [2]:
#整除
a = tf.range(5)
b = tf.constant(2)
a//b

<tf.Tensor: id=5, shape=(5,), dtype=int32, numpy=array([0, 0, 1, 1, 2], dtype=int32)>

In [3]:
#余除
a%b

<tf.Tensor: id=6, shape=(5,), dtype=int32, numpy=array([0, 1, 0, 1, 0], dtype=int32)>

乘方
通过 tf.pow(x, a)可以方便地完成𝑦 = 𝑥𝑎乘方运算

In [4]:
x = tf.range(4)
tf.pow(x,3)

<tf.Tensor: id=12, shape=(4,), dtype=int32, numpy=array([ 0,  1,  8, 27], dtype=int32)>

In [5]:
x**2

<tf.Tensor: id=14, shape=(4,), dtype=int32, numpy=array([0, 1, 4, 9], dtype=int32)>

设置指数为1
𝑎
形式即可实现根号运算： 𝑎√𝑥:

In [2]:
x = tf.constant([1.,4.,9.])
x**(0.5)

<tf.Tensor: id=2, shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

对于常见的平方和平方根运算，可以使用 tf.square(x)和 tf.sqrt(x)实现。

In [4]:
x = tf.range(5)
x = tf.cast(x,dtype=tf.float32)
x = tf.square(x)
x

<tf.Tensor: id=14, shape=(5,), dtype=float32, numpy=array([ 0.,  1.,  4.,  9., 16.], dtype=float32)>

平方根运算

In [5]:
x = tf.range(5)
x = tf.cast(x,dtype=tf.float32)
tf.sqrt(x)

<tf.Tensor: id=20, shape=(5,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       ],
      dtype=float32)>

指数、对数

In [6]:
x = tf.constant([1.,2.,3.])
2**x

<tf.Tensor: id=23, shape=(3,), dtype=float32, numpy=array([2., 4., 8.], dtype=float32)>

自然指数𝑒𝑥,可以通过 tf.exp(x)实现

In [8]:
tf.exp(1.)

<tf.Tensor: id=25, shape=(), dtype=float32, numpy=2.7182817>

自然对数l g𝑒 𝑥可以通过 tf.math.log(x)实现

In [9]:
x = tf.exp(3.)
x

<tf.Tensor: id=27, shape=(), dtype=float32, numpy=20.085537>

In [10]:
tf.math.log(x)

<tf.Tensor: id=28, shape=(), dtype=float32, numpy=3.0>

计算以10为底的对数

In [11]:
x =tf.constant([1.,2.])
x = 10**x

In [12]:
tf.math.log(x)/tf.math.log(10.)

<tf.Tensor: id=35, shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

矩阵相乘

In [14]:
a = tf.random.normal([4,3,23,32])
b = tf.random.normal([4,3,32,2])
a@b

<tf.Tensor: id=48, shape=(4, 3, 23, 2), dtype=float32, numpy=
array([[[[ 5.36142778e+00, -7.63391447e+00],
         [-8.13161182e+00, -3.37928057e+00],
         [ 5.10068941e+00,  2.89371401e-01],
         [ 6.76951122e+00, -3.38673282e+00],
         [ 1.28785586e+00,  5.83694577e-01],
         [-2.01724911e+00,  8.53647709e+00],
         [-2.46087766e+00, -6.64590836e+00],
         [ 3.80394006e+00, -1.05258856e+01],
         [-1.19289052e+00, -4.62121534e+00],
         [ 1.16204987e+01, -1.91339171e+00],
         [-7.06598759e-01,  4.68734932e+00],
         [ 1.36194324e+00,  1.30687456e+01],
         [ 5.66284478e-01,  1.91527915e+00],
         [-2.35059094e+00, -6.66120172e-01],
         [-3.42129350e+00,  4.62361956e+00],
         [ 5.88700294e-01,  3.23044682e+00],
         [ 5.58418798e+00,  3.11474061e+00],
         [ 7.01861668e+00,  2.89567590e+00],
         [ 8.15403557e+00,  6.44295979e+00],
         [-7.75463045e-01, -2.89832622e-01],
         [ 1.47389150e+00, -4.42375278

In [15]:
a = tf.random.normal([4,28,32])
b = tf.random.normal([32,16])
tf.matmul(a,b)

<tf.Tensor: id=61, shape=(4, 28, 16), dtype=float32, numpy=
array([[[ -4.0097384 ,  -3.3730273 ,   2.4742963 , ...,   3.2784634 ,
           3.4453728 ,   0.74361223],
        [  3.8881094 ,  -2.9687006 ,  -1.4042104 , ...,  -5.3200927 ,
           2.8818586 ,   0.999687  ],
        [ -1.7863661 ,   3.7590783 ,  -2.5734065 , ...,   0.08829321,
          -8.479588  ,  -4.4944077 ],
        ...,
        [  1.3942804 ,  -0.21255888,  -2.3071034 , ...,   2.8306074 ,
           5.6445827 ,  -0.04177273],
        [  4.923064  ,  -8.429109  ,   5.970341  , ...,  -1.7201548 ,
          -1.923564  ,  -4.50334   ],
        [  2.3035262 ,  -3.5170922 ,  10.589119  , ...,  -2.631158  ,
           2.6016195 ,   1.5252385 ]],

       [[ -2.85755   ,  -2.1062346 ,  -5.453834  , ...,  -4.668476  ,
          -2.0358803 ,  -1.5413111 ],
        [ -7.5853667 ,  -7.9079447 ,   3.983818  , ...,  -8.353443  ,
          -3.1452534 ,  -5.0798078 ],
        [ -5.014997  ,  13.625356  ,  -2.0488937 , ...,  -5.1